<?xml version="1.0" encoding="UTF-8"?>
<testsuites name="Mocha Tests" time="3.211" tests="6" failures="3">
  <testsuite name="Root Suite" timestamp="2023-11-11T03:58:38" tests="0" file="cypress\e2e\api_test.cy.js" time="0.000" failures="0">
  </testsuite>
  <testsuite name="API Testing ATMATECH" timestamp="2023-11-11T03:58:38" tests="0" time="0.000" failures="0">
  </testsuite>
  <testsuite name="Login Endpoint" timestamp="2023-11-11T03:58:38" tests="1" time="0.386" failures="0">
    <testcase name="API Testing ATMATECH Login Endpoint Negatif Case: Login with invalid credential" time="0.337" classname="Negatif Case: Login with invalid credential">
    </testcase>
  </testsuite>
  <testsuite name="User Detail Login" timestamp="2023-11-11T03:58:38" tests="3" time="1.425" failures="1">
    <testcase name="API Testing ATMATECH User Detail Login Positif Case: Get User Detail with valid access token" time="0.000" classname="Positif Case: Get User Detail with valid access token">
      <failure message="`cy.request()` failed on:

https://qc-test.atmatech.id/api/me/

The response we received from your web server was:

  &gt; 401: Unauthorized

This was considered a failure because the status code was not `2xx` or `3xx`.

If you do not want status codes to cause failures pass the option: `failOnStatusCode: false`

-----------------------------------------------------------

The request we sent was:

Method: GET
URL: https://qc-test.atmatech.id/api/me/
Headers: {
  &quot;Connection&quot;: &quot;keep-alive&quot;,
  &quot;Authorization&quot;: &quot;Bearer undefined&quot;,
  &quot;user-agent&quot;: &quot;Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Cypress/13.5.0 Chrome/114.0.5735.289 Electron/25.8.4 Safari/537.36&quot;,
  &quot;accept&quot;: &quot;*/*&quot;,
  &quot;accept-encoding&quot;: &quot;gzip, deflate&quot;
}

-----------------------------------------------------------

The response we got was:

Status: 401 - Unauthorized
Headers: {
  &quot;date&quot;: &quot;Sat, 11 Nov 2023 03:58:41 GMT&quot;,
  &quot;content-type&quot;: &quot;application/json; charset=UTF-8&quot;,
  &quot;content-length&quot;: &quot;27&quot;,
  &quot;connection&quot;: &quot;keep-alive&quot;,
  &quot;vary&quot;: &quot;Origin&quot;,
  &quot;cf-cache-status&quot;: &quot;DYNAMIC&quot;,
  &quot;report-to&quot;: &quot;{\&quot;endpoints\&quot;:[{\&quot;url\&quot;:\&quot;https:\\/\\/a.nel.cloudflare.com\\/report\\/v3?s=QonasoSEG%2FcY4BnXnayYpEGNwG6wkbVNxOSWP13Dzs5FbCAMRdOclo46nFnx1Fw1WSgXZPQR06aQlGEVzwTwQzH6014iysbhxb%2FqMlzgdgloo6vFotPG43tsWv1o1C7e8oL4jf4Y\&quot;}],\&quot;group\&quot;:\&quot;cf-nel\&quot;,\&quot;max_age\&quot;:604800}&quot;,
  &quot;nel&quot;: &quot;{\&quot;success_fraction\&quot;:0,\&quot;report_to\&quot;:\&quot;cf-nel\&quot;,\&quot;max_age\&quot;:604800}&quot;,
  &quot;server&quot;: &quot;cloudflare&quot;,
  &quot;cf-ray&quot;: &quot;82439e423ef3354f-CGK&quot;,
  &quot;alt-svc&quot;: &quot;h3=\&quot;:443\&quot;; ma=86400&quot;
}
Body: {
  &quot;message&quot;: &quot;Unauthorized&quot;
}


https://on.cypress.io/request" type="CypressError"><![CDATA[CypressError: `cy.request()` failed on:

https://qc-test.atmatech.id/api/me/

The response we received from your web server was:

  > 401: Unauthorized

This was considered a failure because the status code was not `2xx` or `3xx`.

If you do not want status codes to cause failures pass the option: `failOnStatusCode: false`

-----------------------------------------------------------

The request we sent was:

Method: GET
URL: https://qc-test.atmatech.id/api/me/
Headers: {
  "Connection": "keep-alive",
  "Authorization": "Bearer undefined",
  "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Cypress/13.5.0 Chrome/114.0.5735.289 Electron/25.8.4 Safari/537.36",
  "accept": "*/*",
  "accept-encoding": "gzip, deflate"
}

-----------------------------------------------------------

The response we got was:

Status: 401 - Unauthorized
Headers: {
  "date": "Sat, 11 Nov 2023 03:58:41 GMT",
  "content-type": "application/json; charset=UTF-8",
  "content-length": "27",
  "connection": "keep-alive",
  "vary": "Origin",
  "cf-cache-status": "DYNAMIC",
  "report-to": "{\"endpoints\":[{\"url\":\"https:\\/\\/a.nel.cloudflare.com\\/report\\/v3?s=QonasoSEG%2FcY4BnXnayYpEGNwG6wkbVNxOSWP13Dzs5FbCAMRdOclo46nFnx1Fw1WSgXZPQR06aQlGEVzwTwQzH6014iysbhxb%2FqMlzgdgloo6vFotPG43tsWv1o1C7e8oL4jf4Y\"}],\"group\":\"cf-nel\",\"max_age\":604800}",
  "nel": "{\"success_fraction\":0,\"report_to\":\"cf-nel\",\"max_age\":604800}",
  "server": "cloudflare",
  "cf-ray": "82439e423ef3354f-CGK",
  "alt-svc": "h3=\":443\"; ma=86400"
}
Body: {
  "message": "Unauthorized"
}


https://on.cypress.io/request
    at <unknown> (https://qc-test.atmatech.id/__cypress/runner/cypress_runner.js:133362:72)
    at tryCatcher (https://qc-test.atmatech.id/__cypress/runner/cypress_runner.js:1807:23)
    at Promise._settlePromiseFromHandler (https://qc-test.atmatech.id/__cypress/runner/cypress_runner.js:1519:31)
    at Promise._settlePromise (https://qc-test.atmatech.id/__cypress/runner/cypress_runner.js:1576:18)
    at Promise._settlePromise0 (https://qc-test.atmatech.id/__cypress/runner/cypress_runner.js:1621:10)
    at Promise._settlePromises (https://qc-test.atmatech.id/__cypress/runner/cypress_runner.js:1701:18)
    at _drainQueueStep (https://qc-test.atmatech.id/__cypress/runner/cypress_runner.js:2407:12)
    at _drainQueue (https://qc-test.atmatech.id/__cypress/runner/cypress_runner.js:2400:9)
    at Async._drainQueues (https://qc-test.atmatech.id/__cypress/runner/cypress_runner.js:2416:5)
    at Async.drainQueues (https://qc-test.atmatech.id/__cypress/runner/cypress_runner.js:2286:14)
From Your Spec Code:
    at Context.eval (webpack:///./cypress/e2e/api_test.cy.js:48:15)]]></failure>
    </testcase>
    <testcase name="API Testing ATMATECH User Detail Login Negative Case: Access API User detail without token" time="0.154" classname="Negative Case: Access API User detail without token">
    </testcase>
    <testcase name="API Testing ATMATECH User Detail Login Negatif Case: Unauthorized access to Detail" time="0.174" classname="Negatif Case: Unauthorized access to Detail">
    </testcase>
  </testsuite>
  <testsuite name="Users Endpoint" timestamp="2023-11-11T03:58:40" tests="2" time="1.375" failures="2">
    <testcase name="API Testing ATMATECH Users Endpoint Positive Case: Get data User based on criteria" time="0.000" classname="Positive Case: Get data User based on criteria">
      <failure message="`cy.request()` failed on:

https://qc-test.atmatech.id/api/user/?q=&amp;role=user&amp;page=1&amp;limit=10

The response we received from your web server was:

  &gt; 401: Unauthorized

This was considered a failure because the status code was not `2xx` or `3xx`.

If you do not want status codes to cause failures pass the option: `failOnStatusCode: false`

-----------------------------------------------------------

The request we sent was:

Method: GET
URL: https://qc-test.atmatech.id/api/user/?q=&amp;role=user&amp;page=1&amp;limit=10
Headers: {
  &quot;Connection&quot;: &quot;keep-alive&quot;,
  &quot;Authorization&quot;: &quot;Bearer undefined&quot;,
  &quot;user-agent&quot;: &quot;Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Cypress/13.5.0 Chrome/114.0.5735.289 Electron/25.8.4 Safari/537.36&quot;,
  &quot;accept&quot;: &quot;*/*&quot;,
  &quot;accept-encoding&quot;: &quot;gzip, deflate&quot;
}

-----------------------------------------------------------

The response we got was:

Status: 401 - Unauthorized
Headers: {
  &quot;date&quot;: &quot;Sat, 11 Nov 2023 03:58:42 GMT&quot;,
  &quot;content-type&quot;: &quot;application/json; charset=UTF-8&quot;,
  &quot;content-length&quot;: &quot;27&quot;,
  &quot;connection&quot;: &quot;keep-alive&quot;,
  &quot;vary&quot;: &quot;Origin&quot;,
  &quot;cf-cache-status&quot;: &quot;DYNAMIC&quot;,
  &quot;report-to&quot;: &quot;{\&quot;endpoints\&quot;:[{\&quot;url\&quot;:\&quot;https:\\/\\/a.nel.cloudflare.com\\/report\\/v3?s=ZM9VDRVnB8uUkgySU8RFRElbYB%2FulP7hSssLAo%2B%2BrjfxHBvDUT%2B5l1X7yAyaZ4RXRfy86wo5BegGU5NlYoVuW55ysAbiXK7F49j7SLcGljexBdGGRRBSjZthcGu8hU9boowio3VW\&quot;}],\&quot;group\&quot;:\&quot;cf-nel\&quot;,\&quot;max_age\&quot;:604800}&quot;,
  &quot;nel&quot;: &quot;{\&quot;success_fraction\&quot;:0,\&quot;report_to\&quot;:\&quot;cf-nel\&quot;,\&quot;max_age\&quot;:604800}&quot;,
  &quot;server&quot;: &quot;cloudflare&quot;,
  &quot;cf-ray&quot;: &quot;82439e4c1d0c354f-CGK&quot;,
  &quot;alt-svc&quot;: &quot;h3=\&quot;:443\&quot;; ma=86400&quot;
}
Body: {
  &quot;message&quot;: &quot;Unauthorized&quot;
}


https://on.cypress.io/request" type="CypressError"><![CDATA[CypressError: `cy.request()` failed on:

https://qc-test.atmatech.id/api/user/?q=&role=user&page=1&limit=10

The response we received from your web server was:

  > 401: Unauthorized

This was considered a failure because the status code was not `2xx` or `3xx`.

If you do not want status codes to cause failures pass the option: `failOnStatusCode: false`

-----------------------------------------------------------

The request we sent was:

Method: GET
URL: https://qc-test.atmatech.id/api/user/?q=&role=user&page=1&limit=10
Headers: {
  "Connection": "keep-alive",
  "Authorization": "Bearer undefined",
  "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Cypress/13.5.0 Chrome/114.0.5735.289 Electron/25.8.4 Safari/537.36",
  "accept": "*/*",
  "accept-encoding": "gzip, deflate"
}

-----------------------------------------------------------

The response we got was:

Status: 401 - Unauthorized
Headers: {
  "date": "Sat, 11 Nov 2023 03:58:42 GMT",
  "content-type": "application/json; charset=UTF-8",
  "content-length": "27",
  "connection": "keep-alive",
  "vary": "Origin",
  "cf-cache-status": "DYNAMIC",
  "report-to": "{\"endpoints\":[{\"url\":\"https:\\/\\/a.nel.cloudflare.com\\/report\\/v3?s=ZM9VDRVnB8uUkgySU8RFRElbYB%2FulP7hSssLAo%2B%2BrjfxHBvDUT%2B5l1X7yAyaZ4RXRfy86wo5BegGU5NlYoVuW55ysAbiXK7F49j7SLcGljexBdGGRRBSjZthcGu8hU9boowio3VW\"}],\"group\":\"cf-nel\",\"max_age\":604800}",
  "nel": "{\"success_fraction\":0,\"report_to\":\"cf-nel\",\"max_age\":604800}",
  "server": "cloudflare",
  "cf-ray": "82439e4c1d0c354f-CGK",
  "alt-svc": "h3=\":443\"; ma=86400"
}
Body: {
  "message": "Unauthorized"
}


https://on.cypress.io/request
    at <unknown> (https://qc-test.atmatech.id/__cypress/runner/cypress_runner.js:133362:72)
    at tryCatcher (https://qc-test.atmatech.id/__cypress/runner/cypress_runner.js:1807:23)
    at Promise._settlePromiseFromHandler (https://qc-test.atmatech.id/__cypress/runner/cypress_runner.js:1519:31)
    at Promise._settlePromise (https://qc-test.atmatech.id/__cypress/runner/cypress_runner.js:1576:18)
    at Promise._settlePromise0 (https://qc-test.atmatech.id/__cypress/runner/cypress_runner.js:1621:10)
    at Promise._settlePromises (https://qc-test.atmatech.id/__cypress/runner/cypress_runner.js:1701:18)
    at _drainQueueStep (https://qc-test.atmatech.id/__cypress/runner/cypress_runner.js:2407:12)
    at _drainQueue (https://qc-test.atmatech.id/__cypress/runner/cypress_runner.js:2400:9)
    at Async._drainQueues (https://qc-test.atmatech.id/__cypress/runner/cypress_runner.js:2416:5)
    at Async.drainQueues (https://qc-test.atmatech.id/__cypress/runner/cypress_runner.js:2286:14)
From Your Spec Code:
    at Context.eval (webpack:///./cypress/e2e/api_test.cy.js:138:15)]]></failure>
    </testcase>
    <testcase name="API Testing ATMATECH Users Endpoint Negative Case: Access API user list without token" time="0.000" classname="Negative Case: Access API user list without token">
      <failure message="expected 404 to equal 401" type="AssertionError"><![CDATA[AssertionError: expected 404 to equal 401
    at Context.eval (webpack:///./cypress/e2e/api_test.cy.js:163:43)

      + expected - actual

      -404
      +401
      ]]></failure>
    </testcase>
  </testsuite>
</testsuites>